name: Zones
version: 0.2
author: Sabersamus
main: info.bytecraft.zones.Zones
description: >
    The zones plugin for the server Bytecraft
database: true
commands:
    zone:
        description: manage the zones
        usage: |
            /<command> create [name]
            /<command> adduser [zone] [player] [rank]
            /<command> deluser [zone] [player]
            /<command> delete [name]
            /<command> pvp [zone] [true|false]
            /<command> whitelist [zone] [true|false]
            /<command> enter [zone] [message]
            /<command> exit [zone] [message]
            /<command> destroy [zone] [true|false]
            /<command> place [zone] [true|false]
    lot:
        description: manage lots
        usage: |
            /<command> [create] [name] [owner]
    town:
        description: manage the current zone you are in
        usage: |
            /<command> delete
            /<command> adduser [player] [rank]
            /<command> deluser [player]
            /<command> delete [name]
            /<command> pvp [true|false]
            /<command> whitelist [true|false]
            /<command> enter [message]
            /<command> exit [message]
            /<command> destroy [true|false]
            /<command> place [true|false]
permissions:
    bytecraft.zones.admin:
        description: All permissions to zones
        default: op
        children:
            bytecraft.zones.create: true
            bytecraft.zones.delete: true
            bytecraft.zones.whitelist: true
            bytecraft.zones.adduser: true
            bytecraft.zones.deluser: true
            bytecraft.zones.select: true
            bytecraft.zones.pvp: true
            bytecraft.zones.messages: true
            bytecraft.zones.buildmanage: true
            bytecraft.zones.lot: true